### ISSUE TITLE
ANC Frame Element's Packet Boundary Calculation Error

### ISSUE THREAD

**Issue by ujinyang** [Myriadbits/MXFInspect#9]
I found a problem that incorrectly analyzes the ANC Frame Element while using MXF Inspect.
If the element is a CDP, AFD, OP47 packet, then the next element is calculated incorrectly.

![image](https://user-images.githubusercontent.com/1154953/208233499-35b8cab8-5716-4201-9f41-8d72e8f9c9eb.png)

The problematic part is the source below, and I also included the modifications I made, but I don't know if there is a better way to fix it.

			// Length Alignment
			this.Length = 4 * ((this.Length + 3) / 4);

			// FIX : calculate end of packet position
			long packetEndPosition = reader.Position + this.Length;

			if (this.Length > 3)
			{
				// Read the DID
				this.DID = reader.ReadB();
				this.SDID = reader.ReadB();
				this.Size = reader.ReadB();

				UInt16 combinedID = (UInt16)((((UInt16)this.DID) << 8) | this.SDID);
				if (m_DIDDescription.ContainsKey(combinedID))
					this.ContentDescription = m_DIDDescription[combinedID];
				else
					this.ContentDescription = "<unknown content>";

				switch (combinedID)
				{
					case 0x6101: // CDP
						this.AddChild(new MXFCDPPacket(reader));
						break;
					case 0x4105: // AFD
						break;
					case 0x4302: // OP47
						break;
					default:
						// Read the real payload without the did/sdid/size
						this.Payload = new byte[this.Length - 3];
						reader.Read(this.Payload, this.Length - 3);
						break;
				}
			}

			// FIX : move to packet end position
			if ( reader.Position != packetEndPosition )
				reader.Seek(packetEndPosition);

After modification, it will look like this.

![image](https://user-images.githubusercontent.com/1154953/208234304-1c359b41-1fbb-44bb-9925-041b41e0414d.png)

**Comment by rayden84** [comment]
Hello @ujinyang, would you mind passing me the mxf file in your example? Can you upload it (or a similar, smaller one) somewhere so that I can give a look?

**Comment by ujinyang** [comment]
@rayden84  Thanks for your reply. I have uploaded.

[MxfSampleFile(JustFrontPart)ForAncTesting.zip](https://github.com/Myriadbits/MXFInspect/files/10536905/MxfSampleFile.JustFrontPart.ForAncTesting.zip)

**Comment by rayden84** [comment]
I gave a look at the code in ANC Frame Element and noticed two things:

1) In ANC Packet the two unknown bytes:
https://github.com/Myriadbits/MXFInspect/blob/6f464536f540939f718d4ca06e15eeb6c8354391/MXF/Entries/MXFANCPacket.cs#L133-L134

The first 4 bytes is the number of elements (in our case, size of packet), while the second 4 bytes is element size, as we have byte array it's always  = 1 according to this [blog ](https://mogurenko.com/2015/10/30/closed-captions-and-mxf/). Unfortunately SMPTE 436 is not as clear as it should. 

Since the packet is padded with zeroes to align with double word, these first 4 bytes are the effective length of the packet (thus it is different from PayLoadSampleCount as that is unpadded). With this in mind, we can remove the clumsy code for calculating the packet length and use the value directly. 

2) The problem of the wrongly parsed packs following the first one, happens when the next ANC packet is not CDP, AFD, OP47 because the reader is not set to the correct offset/position (it should be at the end of the current packet, thus also the correct packet length is needed as mentioned in 1) ). This can be corrected in the ANC packet directly, but I think it is cleaner to handle this in ANC Frame Element:
https://github.com/rayden84/MXFInspect/blob/74241a19f700bb59044edadccd94db461d4387e1/MXF/MainElements/MXFANCFrameElement.cs#L44

The packetBegin position is saved on every new packet, and the reader is moved to the end of the packet after being parsed.

I made the modifications in my [fork ](https://github.com/rayden84/MXFInspect)as I rewrote a lot of the existing code, and now it seems impossible to merge the changes back to the original project (over 500 commits). I could write a PR, but I never had a response from the original project maintainers. Maybe some day my changes and improvements can be merged back, but for the moment I hope it is okay for you if you just give a look at my fork. Thank you for reporting this issue as it affects also my fork.

**Comment by Myriadbits** [comment]
Hi @rayden84, I see that you have been very busy over the years extending this MXFInspect project. Good work! When I made this tool, I was working in the broadcast industry and was missing a good tool to view the internals of MXF files, so I made this as a kind of side project. I left the industry 7 or 8 years back and didn't have anything todo with MXF files anymore (working on something completely different now: Charging Stations for EV's). It's nice to hear that some folks in the industry still use it and that you are still expanding the tool. 
Do you want me to update the original repo to your latest master branch?

**Comment by rayden84** [comment]
Hi @Myriadbits, glad to hear from you. Yes, I had some free time to improve the original project, but you laid the cornerstone for a wonderful tool for the industry (and probably the only free & open source tool available). It is even linked in this _awesome_ [list ](https://github.com/ebu/awesome-broadcasting) from EBU. Probably the most added value of my work is the migration to .NET6, as the old framework is deprecated. It would be great if my commits could be integrated back, however there are two little aspects to think about:
1) I must admit that my master branch is not as polished and clean as it should at the moment. I need some time to fix things, as I had the bad idea to work on multiple issues contemporarily, and my git history is everything but clean (and never will be, sorry). 

2) Second problem is (and I simply don't have enough experience in this matter) the copyright/license. As I did not know how to proceed, I simply copied your source code copyright preamble (the one from 2015) in every new file and never mentioned myself. To be crystal clear: it is not about me, but the ones that are already collaborating on the project (don't know if still actively) should be given credit for. Furthermore, I would like to mention open source frameworks I have used/I will use for the project, like [Serilog](https://github.com/serilog/serilog) (and hopefully soon I will use this [hex viewer](https://github.com/themeldingwars/Be.HexEditor)). So in my opinion, an updated About form is mandatory.

What do you think about it? Shall we bring the master branch to my latest master branch anyway and thereafter work out the above described problems?

**Comment by Myriadbits** [comment]
Hi @rayden84, sounds like a good idea! Let's integrate your master branch into this repo. And as you said, indeed update the license and mention all integrated libs. Of course updating the About and mentioning all contributors should also be done. 
I'm curious how the application has grown :)
To be honest, I didn't know this application was used so often and that it was forked so many times. I dropped it on github hoping someone might find it useful. I didn't expect this response.

I'll start on it this weekend.
